In [ ]:
import numpy as np #np is the alias name

In [ ]:
list1=[2,5,24,2,]
list2=[5,6,8,79,75]
import numpy as np #np is the alias name

In [ ]:
import numpy as np #np is the alias name

In [ ]:
my_list=[1,5,4,6,9]

In [ ]:
my_list=[1,5,4,6,9]
type(my_list)

list

In [ ]:
my_list=[1,5,4,6,9]
arr=np.array(my_list)
print(arr)

[1 5 4 6 9]


In [ ]:
#multinested array
my_list=[1,5,4,6,9]
my_list1=[1,5,8,6,7]
my_list2=[2,7,3,6,7]
arr_new=np.array([my_list,my_list1,my_list])
print(arr_new)


[[1 5 4 6 9]
 [1 5 8 6 7]
 [1 5 4 6 9]]


In [ ]:
arr_new=np.array([my_list,my_list1,my_list])
print(arr_new)

[[1 5 4 6 9]
 [1 5 8 6 7]
 [1 5 4 6 9]]


In [ ]:
arr_new.shape
print(arr_new)

[[1 5 4 6 9]
 [1 5 8 6 7]
 [1 5 4 6 9]]


In [ ]:
arr_new.reshape(5,3)

array([[1, 5, 4],
       [6, 9, 1],
       [5, 8, 6],
       [7, 1, 5],
       [4, 6, 9]])

In [ ]:
#generating random numbers
arr=np.arange(0,10,1)

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.random.rand(3,4)

array([[0.19283877, 0.81191955, 0.08754613, 0.996155  ],
       [0.05662677, 0.31121509, 0.0384921 , 0.74720832],
       [0.6397274 , 0.61588137, 0.94759797, 0.59286966]])

In [ ]:
np.random.randint(0,20,10)

array([ 8,  5,  1, 14,  4, 19,  5, 17,  1,  8])

In [ ]:
import pandas as pd
#reading a dataset


In [ ]:
data=pd.read_csv("/content/12th data Karad final csv.csv")

In [ ]:
data.head()

SUR NAME FIRST NAME FATHER NAME  PARENT MOBILE DISTRICT
0       MADANE     AADESH     VITTHAL     9503694331   SATARA
1      GHANWAT     AADESH    MAHENDRA     7219496487   SATARA
2  SURYAVANSHI     AADESH      SURESH     9561142657   SATARA
3       BAJARE     AADESH      MAHESH     8275455803   SATARA
4       JADHAV     AADITI      PRATAP     9763834502   SATARA

In [ ]:
data.tail()

SUR NAME FIRST NAME FATHER NAME  PARENT MOBILE DISTRICT
875     LEKAWALE      KARAN      VISHNU     9881455072   SATARA
876      GHADAGE      KARAN      DINKAR     9823192130   SATARA
877  BHINGARDEVE      KARAN   JAGANNATH     9637415187   SATARA
878        PAWAR      KARAN     AVINASH     9049577670   SATARA
879      BEDEKAR      KARAN    JALINDAR     9922182342   SATARA

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   SUR NAME       880 non-null    object
 1   FIRST NAME     880 non-null    object
 2   FATHER NAME    880 non-null    object
 3   PARENT MOBILE  880 non-null    int64 
 4   DISTRICT       880 non-null    object
dtypes: int64(1), object(4)
memory usage: 34.5+ KB


In [ ]:
data.describe()

PARENT MOBILE
count   8.800000e+02
mean    9.102567e+09
std     8.893946e+08
min     3.011953e+09
25%     8.665439e+09
50%     9.422034e+09
75%     9.781245e+09
max     9.975973e+09

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create your own dataset
import numpy as np #np is the alias name

In [ ]:
import numpy as np


In [ ]:
my_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['coln1','coln2','coln3','coln4'])
import numpy as np #np is the alias name

In [ ]:
print(my_data)

      coln1  coln2  coln3  coln4
row1      0      1      2      3
row2      4      5      6      7
row3      8      9     10     11
row4     12     13     14     15
row5     16     17     18     19


In [ ]:
my_data.to_csv('sunday_demo_file.csv')

In [ ]:
my_data.to_excel('sunday_demo_file.xlsx')

In [ ]:
#.loc()
 #.iloc()

In [ ]:
print(my_data)

      coln1  coln2  coln3  coln4
row1      0      1      2      3
row2      4      5      6      7
row3      8      9     10     11
row4     12     13     14     15
row5     16     17     18     19


In [ ]:
my_data.loc['row1']

coln1    0
coln2    1
coln3    2
coln4    3
Name: row1, dtype: int64

In [ ]:
my_data.iloc[2:4,2:]

coln3  coln4
row3     10     11
row4     14     15

In [ ]:
my_data.iloc[3:5,1:3]

coln2  coln3
row4     13     14
row5     17     18

In [ ]:
my_data.iloc[0:3,0:2]

coln2  coln3
row1      1      2
row2      5      6
row3      9     10

In [ ]:
my_data.iloc[0:3,1:3]

coln2  coln3
row1      1      2
row2      5      6
row3      9     10